# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {

  # summarise_omop_snapshot -----
  output$summarise_omop_snapshot_gt <- gt::render_gt({
    OmopSketch::tableOmopSnapshot(data$snapshot)
  })

  # summarise_in_observation -----
  # get data
  getInObservationData <- shiny::reactive({
    data$in_obs |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_in_observation_cdm_name,
        .data$sex %in% input$summarise_in_observation_sex,
        .data$age_group %in% input$summarise_in_observation_age_group,
        .data$variable_name %in% input$summarise_in_observation_variable_name,
        .data$mode %in% input$summarise_in_observation_mode
      )
  })
  output$summarise_in_observation_tidy <- DT::renderDataTable(
    getInObservationData()
  )
  output$summarise_in_observation_ggplot2 <- shiny::renderPlot({
    x <- getInObservationData()

    fx <- input$summarise_in_observation_facet_x
    if (length(fx) > 0) {
      fx <- paste0(fx, collapse = " + ")
    } else {
      fx <- "."
    }
    fy <- input$summarise_in_observation_facet_y
    if (length(fy) > 0) {
      fy <- paste0(fy, collapse = " + ")
    } else {
      fy <- "."
    }
    form <- as.formula(paste0(fy, " ~ ", fx))

    visOmopResults::scatterPlot(
      result = x,
      x = "year",
      y = "count",
      line = TRUE,
      point = TRUE,
      ribbon = FALSE,
      colour = input$summarise_in_observation_colour,
      facet = form
    )
  })

  # summarise_observation_period -----
  # get data
  getObservationPeriodData <- shiny::reactive({
    data$obs_period |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name
      ) |>
      omopgenerics::filterStrata(
        .data$sex %in% input$summarise_observation_period_sex,
        .data$age_group %in% input$summarise_observation_period_age_group
      ) |>
      omopgenerics::filterSettings(
        .data$mode %in% input$summarise_observation_period_mode
      )
  })
  output$summarise_observation_period_gt <- gt::render_gt({
    getObservationPeriodData() |>
      dplyr::filter(.data$estimate_name %in% c("count", "median", "q25", "q75")) |>
      omopgenerics::addSettings(settingsColumn = "mode") |>
      omopgenerics::splitAll() |>
      dplyr::select(!c("variable_level", "observation_period_ordinal", "result_id")) |>
      visOmopResults::visTable(
        estimateName = c(
          "N" = "<count>",
          "median [Q25 - Q75]" = "<median> [<q25> - <q75>]"
        ),
        header = c("cdm_name", "mode"),
        groupColumn = c("age_group", "sex")
      )
  })
  output$summarise_observation_period_ggplot2 <- shiny::renderPlot({
    x <- getObservationPeriodData() |>
      dplyr::filter(.data$estimate_name %in% c("density_x", "density_y"))
    nvars <- length(unique(x$variable_name))
    shiny::validate(shiny::need(nvars == 1, "Only one variable must be provided"))

    x <- x |>
      omopgenerics::tidy()

    fx <- input$summarise_observation_period_facet_x
    if (length(fx) > 0) {
      fx <- paste0(fx, collapse = " + ")
    } else {
      fx <- "."
    }
    fy <- input$summarise_observation_period_facet_y
    if (length(fy) > 0) {
      fy <- paste0(fy, collapse = " + ")
    } else {
      fy <- "."
    }
    form <- as.formula(paste0(fy, " ~ ", fx))

    visOmopResults::scatterPlot(
      result = x,
      x = "density_x",
      y = "density_y",
      line = TRUE,
      point = TRUE,
      ribbon = FALSE,
      colour = input$summarise_observation_period_colour,
      facet = form
    )
  })

}
