# Generated by OmopViewer 0.2.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "https://getlogovector.com/wp-content/uploads/2021/08/health-data-research-uk-hdr-uk-logo-vector.png",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(bootswatch = "cosmo"),
  bslib::nav_panel(
    title = "Background",
    backgroundCard("background.md")
  ),
  ## snapshot ----
  bslib::nav_panel(
    title = "Snapshot",
    bslib::card(
      full_screen = TRUE,
      gt::gt_output("summarise_omop_snapshot_gt")
    )
  ),
  ## summarise in observation
  bslib::nav_panel(
    title = "Summarise in observation",
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_in_observation_cdm_name",
          label = "CDM name",
          choices = cdmNames,
          selected = cdmNames,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_in_observation_sex",
          label = "Sex",
          choices = sexes,
          selected = "overall",
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_in_observation_age_group",
          label = "Age group",
          choices = ageGroups,
          selected = "overall",
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_in_observation_mode",
          label = "Mode",
          choices = modes,
          selected = modes,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_in_observation_variable_name",
          label = "Variable name",
          choices = c("Number person-days", "Number records in observation"),
          selected = "Number person-days",
          multiple = FALSE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            DT::dataTableOutput("summarise_in_observation_tidy")
          )
        ),
        bslib::nav_panel(
          title = "Plot",
          bslib::card(
            full_screen = TRUE,
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_in_observation_facet_x",
                  label = "Facet x",
                  choices = c("cdm_name", "age_group", "sex", "mode"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_in_observation_facet_y",
                  label = "Facet y",
                  choices = c("cdm_name", "age_group", "sex", "mode"),
                  selected = c("age_group", "sex"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_in_observation_colour",
                  label = "Colour",
                  choices = c("cdm_name", "age_group", "sex", "mode"),
                  selected = "mode",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_in_observation_ggplot2")
            )
          )
        )
      )
    )
  ),
  ## summarise observation period ----
  bslib::nav_panel(
    title = "Observation period",
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_observation_period_cdm_name",
          label = "CDM name",
          choices = cdmNames,
          selected = cdmNames,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_observation_period_mode",
          label = "Mode",
          choices = modes,
          selected = modes,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_observation_period_variable_name",
          label = "Variable name",
          choices = data$obs_period$variable_name |> unique(),
          selected = data$obs_period$variable_name |> unique(),
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table observation period",
          bslib::card(
            full_screen = TRUE,
            gt::gt_output("summarise_observation_period_gt")
          )
        ),
        bslib::nav_panel(
          title = "Plot observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_facet",
                  label = "Facet x",
                  choices = c("cdm_name", "mode"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_colour",
                  label = "Colour",
                  choices = c("cdm_name", "mode"),
                  selected = "mode",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_x_max",
                  label = "X max",
                  value = -1
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_observation_period_ggplot2")
            )
          )
        )
      )
    )
  ),
  ## incidence ----
  bslib::nav_panel(
    title = "Incidence",
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "incidence_cdm_name",
          label = "CDM name",
          choices = cdmNames,
          selected = cdmNames,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "incidence_age_group",
          label = "Age group",
          choices = ageGroups,
          selected = "overall",
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "incidence_sex",
          label = "Sex",
          choices = sexes,
          selected = "overall",
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "incidence_mode",
          label = "Mode",
          choices = modes,
          selected = modes,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "incidence_interval",
          label = "Interval",
          choices = c("overall", "years"),
          selected = "overall",
          multiple = FALSE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "incidence_outcome",
          label = "Outcome",
          choices = data$incidence$outcome |> unique(),
          selected = data$incidence$outcome |> unique() |> dplyr::first(),
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Incidence",
          bslib::card(
            full_screen = TRUE,
            gt::gt_output("incidence_gt")
          )
        ),
        bslib::nav_panel(
          title = "Plot Incidence",
          bslib::card(
            full_screen = TRUE,
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "incidence_x",
                  label = "x",
                  choices = c("cdm_name", "outcome", "age_group", "sex", "year", "mode"),
                  selected = "year",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "incidence_facet_x",
                  label = "Facet x",
                  choices = c("cdm_name", "outcome", "age_group", "sex", "year", "mode"),
                  selected = c("age_group", "sex"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "incidence_facet_y",
                  label = "Facet y",
                  choices = c("cdm_name", "outcome", "age_group", "sex", "year", "mode"),
                  selected = c("cdm_name"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "incidence_colour",
                  label = "Colour",
                  choices = c("cdm_name", "outcome", "age_group", "sex", "year", "mode"),
                  selected = "mode",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::plotOutput("incidence_ggplot2")
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
