# Generated by OmopViewer 0.2.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    summaryCard(data)
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_omop_snapshot_grouping_cdm_name,
              selected = filterValues$summarise_omop_snapshot_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_variable_name",
              label = "Variable name",
              choices = filterValues$summarise_omop_snapshot_variable_name,
              selected = filterValues$summarise_omop_snapshot_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_estimate_name",
              label = "Estimate name",
              choices = filterValues$summarise_omop_snapshot_estimate_name,
              selected = filterValues$summarise_omop_snapshot_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_tidy_columns",
                  label = "Columns",
                  choices = filterValues$summarise_omop_snapshot_tidy_columns,
                  selected = filterValues$summarise_omop_snapshot_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "summarise_omop_snapshot_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_omop_snapshot_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Snapshot table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_gt_17_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_omop_snapshot_gt_17")
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise in observation",
    icon = shiny::icon(""),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p(character())
          ),
          bslib::accordion_panel(
            title = "Settings",
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_settings_interval",
              label = "Interval",
              choices = filterValues$summarise_in_observation_settings_interval,
              selected = filterValues$summarise_in_observation_settings_interval,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_settings_mode",
              label = "Mode",
              choices = filterValues$summarise_in_observation_settings_mode,
              selected = filterValues$summarise_in_observation_settings_mode,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_in_observation_grouping_cdm_name,
              selected = filterValues$summarise_in_observation_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_grouping_omop_table",
              label = "Omop table",
              choices = filterValues$summarise_in_observation_grouping_omop_table,
              selected = filterValues$summarise_in_observation_grouping_omop_table,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_grouping_sex",
              label = "Sex",
              choices = filterValues$summarise_in_observation_grouping_sex,
              selected = filterValues$summarise_in_observation_grouping_sex,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_grouping_age_group",
              label = "Age group",
              choices = filterValues$summarise_in_observation_grouping_age_group,
              selected = filterValues$summarise_in_observation_grouping_age_group,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_grouping_time_interval",
              label = "Time interval",
              choices = filterValues$summarise_in_observation_grouping_time_interval,
              selected = filterValues$summarise_in_observation_grouping_time_interval,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_variable_name",
              label = "Variable name",
              choices = filterValues$summarise_in_observation_variable_name,
              selected = filterValues$summarise_in_observation_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "summarise_in_observation_estimate_name",
              label = "Estimate name",
              choices = filterValues$summarise_in_observation_estimate_name,
              selected = filterValues$summarise_in_observation_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_in_observation_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_in_observation_tidy_columns",
                  label = "Columns",
                  choices = filterValues$summarise_in_observation_tidy_columns,
                  selected = filterValues$summarise_in_observation_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "summarise_in_observation_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_in_observation_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Formatted",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_in_observation_gt_0_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_in_observation_gt_0_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("omop_table", "sex", "age_group", "time_interval", "variable_name", "variable_level", "estimate_name", "interval", "mode"),
                    input_id = "summarise_in_observation_gt_0_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = "cdm_name",
                    input_id = "summarise_in_observation_gt_0_header"
                  ),
                  sortable::add_rank_list(
                    text = "group",
                    labels = character(),
                    input_id = "summarise_in_observation_gt_0_group"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = character(),
                    input_id = "summarise_in_observation_gt_0_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_in_observation_gt_0")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Observation period",
    icon = shiny::icon("eye"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Settings",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_settings_mode",
              label = "Mode",
              choices = filterValues$summarise_observation_period_settings_mode,
              selected = filterValues$summarise_observation_period_settings_mode,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_observation_period_grouping_cdm_name,
              selected = filterValues$summarise_observation_period_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_grouping_observation_period_ordinal",
              label = "Observation period ordinal",
              choices = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
              selected = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_grouping_age_group",
              label = "Age group",
              choices = filterValues$summarise_observation_period_grouping_age_group,
              selected = filterValues$summarise_observation_period_grouping_age_group,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_grouping_sex",
              label = "Sex",
              choices = filterValues$summarise_observation_period_grouping_sex,
              selected = filterValues$summarise_observation_period_grouping_sex,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_variable_name",
              label = "Variable name",
              choices = filterValues$summarise_observation_period_variable_name,
              selected = filterValues$summarise_observation_period_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_estimate_name",
              label = "Estimate name",
              choices = filterValues$summarise_observation_period_estimate_name,
              selected = filterValues$summarise_observation_period_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_observation_period_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_tidy_columns",
                  label = "Columns",
                  choices = filterValues$summarise_observation_period_tidy_columns,
                  selected = filterValues$summarise_observation_period_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "summarise_observation_period_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_observation_period_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_gt_15_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_observation_period_gt_15_download", label = "Download")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_observation_period_gt_15")
          )
        ),
        bslib::nav_panel(
          title = "Plot observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_height",
                  label = "Height",
                  value = 10
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_dpi",
                  label = "dpi",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_observation_period_ggplot2_16_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_variableName",
                  label = "variableName",
                  selected = "Number subjects",
                  multiple = ,
                  choices = c("number subjects", "records per person", "duration in days", "days to next observation period"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_plotType",
                  label = "plotType",
                  selected = "barplot",
                  multiple = ,
                  choices = c("barplot", "boxplot", "densityplot"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_facet",
                  label = "facet",
                  selected = NULL,
                  multiple = TRUE,
                  choices = c("cdm_name", "observation_period_ordinal", "age_group", "sex"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_observation_period_ggplot2_16")
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.2.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
